version: '3.3'

services:
  amq:
    image: vromero/activemq-artemis:latest-alpine
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - 8161:8161
      - 61616:61616
      - 61617:61617