version: '3.3'

services:
  amq:
    image: vromero/activemq-artemis:latest-alpine
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - 8161:8161
      - 61616:61616
      - 61617:61617

  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 60s
    environment:
      POSTGRES_PASSWORD: appusr
      POSTGRES_USER: appusr
      POSTGRES_DB: product
#    volumes:
#      - ./postgres/data:/var/lib/postgresql/data