spring:
  application:
    name: spring-boot-amq-producer-test
  main:
    banner-mode: 'off'
    lazy-initialization: true
  activemq:
    broker-url: failover:(tcp://localhost:61616)?initialReconnectDelay=100
    pool:
      enabled: true
  jms:
    pub-sub-domain: false
  sleuth:
    messaging:
      jms:
        enabled: false
springdoc:
  swagger-ui:
    operationsSorter=method: